// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlbridge

import (
	"context"
)

const countWorlds = `-- name: CountWorlds :one
SELECT COUNT(*) FROM world
`

func (q *Queries) CountWorlds(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWorlds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getRandomWorld = `-- name: GetRandomWorld :one
SELECT id, randomnumber FROM world ORDER BY RANDOM() LIMIT 1
`

func (q *Queries) GetRandomWorld(ctx context.Context) (World, error) {
	row := q.db.QueryRowContext(ctx, getRandomWorld)
	var i World
	err := row.Scan(&i.ID, &i.Randomnumber)
	return i, err
}

const getRandomWorlds = `-- name: GetRandomWorlds :many
SELECT id, randomnumber FROM world ORDER BY RANDOM() LIMIT ?
`

func (q *Queries) GetRandomWorlds(ctx context.Context, limit int64) ([]World, error) {
	rows, err := q.db.QueryContext(ctx, getRandomWorlds, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []World
	for rows.Next() {
		var i World
		if err := rows.Scan(&i.ID, &i.Randomnumber); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorld = `-- name: UpdateWorld :exec
UPDATE world SET randomNumber = ? WHERE id = ?
`

type UpdateWorldParams struct {
	Randomnumber int64
	ID           int64
}

func (q *Queries) UpdateWorld(ctx context.Context, arg UpdateWorldParams) error {
	_, err := q.db.ExecContext(ctx, updateWorld, arg.Randomnumber, arg.ID)
	return err
}
