package bindings

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"text/template"
)

type Generator struct {
	OutputDir string
	PkgName   string
}

type BindingData struct {
	PackageName string
	LibName     string
	Functions   []Function
}

func NewGenerator(outputDir, pkgName string) *Generator {
	return &Generator{
		OutputDir: outputDir,
		PkgName:   pkgName,
	}
}

func (g *Generator) Generate(files []*GoFile) error {
	var allFunctions []Function
	for _, f := range files {
		allFunctions = append(allFunctions, f.Functions...)
	}

	if len(allFunctions) == 0 {
		return fmt.Errorf("no exported functions found")
	}

	data := BindingData{
		PackageName: g.PkgName,
		LibName:     getLibName(),
		Functions:   allFunctions,
	}

	if err := g.generateBinding(data); err != nil {
		return err
	}

	if err := g.generateWrapper(data); err != nil {
		return err
	}

	return nil
}

func getLibName() string {
	switch runtime.GOOS {
	case "windows":
		return "_binding.dll"
	case "darwin":
		return "_binding.dylib"
	default:
		return "_binding.so"
	}
}

func (g *Generator) generateBinding(data BindingData) error {
	funcMap := template.FuncMap{
		"cffiDeclParams":  CffiDeclParams,
		"cffiCallArgs":    CffiCallArgs,
		"cffiNewArg":      CffiNewArg,
		"hasSliceParam":   HasSliceParam,
		"returnCountExpr": ReturnCountExpr,
	}

	tmpl := `# Generated by GoFre - DO NOT EDIT

import cffi
import os
import sys
import struct

ffi = cffi.FFI()

def _get_lib_path():
    """Get the path to the shared library."""
    pkg_dir = os.path.dirname(os.path.abspath(__file__))
    lib_name = "{{ .LibName }}"
    return os.path.join(pkg_dir, lib_name)

ffi.cdef("""
{{- range .Functions }}
    {{- $ret := index .Returns 0 }}
    {{- if $ret.IsSlice }}
    {{ $ret.ElemType }}* {{ .Name }}({{ cffiDeclParams .Params }});
    {{- else }}
    {{ $ret.Type }} {{ .Name }}({{ cffiDeclParams .Params }});
    {{- end }}
{{- end }}
""")

_lib = ffi.dlopen(_get_lib_path())

{{- range .Functions }}
{{- $ret := index .Returns 0 }}

def {{ .Name }}({{ range $i, $p := .Params }}{{ if $i }}, {{ end }}{{ $p.Name }}{{ end }}):
    """{{ .Comment }}"""
    {{- if hasSliceParam .Params }}
    {{- range $p := .Params }}{{- if $p.IsSlice }}
    _c_{{ $p.Name }} = ffi.new("{{ $p.ElemType }}[]", {{ $p.Name }})
    {{- end }}{{- end }}
    {{- if $ret.IsSlice }}
    _c_result = _lib.{{ .Name }}({{ cffiNewArg .Params }})
    _count = {{ returnCountExpr .Params $ret }}
    return list(ffi.unpack(_c_result, _count))
    {{- else if eq $ret.Type "char*" }}
    _result = _lib.{{ .Name }}({{ cffiNewArg .Params }})
    return ffi.string(_result).decode('utf-8')
    {{- else }}
    return _lib.{{ .Name }}({{ cffiNewArg .Params }})
    {{- end }}
    {{- else }}
    {{- if $ret.IsSlice }}
    _c_result = _lib.{{ .Name }}({{ cffiCallArgs .Params }})
    _count = {{ returnCountExpr .Params $ret }}
    return list(ffi.unpack(_c_result, _count))
    {{- else if eq $ret.Type "char*" }}
    _result = _lib.{{ .Name }}({{ cffiCallArgs .Params }})
    return ffi.string(_result).decode('utf-8')
    {{- else }}
    return _lib.{{ .Name }}({{ cffiCallArgs .Params }})
    {{- end }}
    {{- end }}
{{- end }}
`

	t, err := template.New("binding").Funcs(funcMap).Parse(tmpl)
	if err != nil {
		return err
	}

	outputPath := filepath.Join(g.OutputDir, "_binding.py")
	f, err := os.Create(outputPath)
	if err != nil {
		return err
	}
	defer f.Close()

	return t.Execute(f, data)
}

func (g *Generator) generateWrapper(data BindingData) error {
	tmpl := `"""{{ .PackageName }} - Go extensions built with GoFre"""

from ._binding import {{ range $i, $f := .Functions }}{{ if $i }}, {{ end }}{{ $f.Name }}{{ end }}

__all__ = [{{ range $i, $f := .Functions }}"{{ $f.Name }}"{{ if not (eq $i (sub (len $.Functions) 1)) }}, {{ end }}{{ end }}]
__version__ = "0.1.0"
`

	t, err := template.New("wrapper").Funcs(template.FuncMap{
		"sub": func(a, b int) int { return a - b },
	}).Parse(tmpl)
	if err != nil {
		return err
	}

	outputPath := filepath.Join(g.OutputDir, "__init__.py")
	f, err := os.Create(outputPath)
	if err != nil {
		return err
	}
	defer f.Close()

	return t.Execute(f, data)
}

// Template functions

// CffiDeclParams generates cffi C declaration parameter list.
func CffiDeclParams(params []Param) string {
	var parts []string
	for _, p := range params {
		if p.IsSlice {
			parts = append(parts, p.ElemType+"* "+p.Name)
			parts = append(parts, "int64_t "+p.Name+"_len")
		} else {
			parts = append(parts, p.Type+" "+p.Name)
		}
	}
	return strings.Join(parts, ", ")
}

// CffiCallArgs generates comma-separated argument list for cffi calls.
func CffiCallArgs(params []Param) string {
	var parts []string
	for _, p := range params {
		parts = append(parts, p.Name)
	}
	return strings.Join(parts, ", ")
}

// CffiNewArg generates arguments using ffi.new for slice parameters.
func CffiNewArg(params []Param) string {
	var parts []string
	for _, p := range params {
		if p.IsSlice {
			parts = append(parts, "_c_"+p.Name+", len("+p.Name+")")
		} else {
			parts = append(parts, p.Name)
		}
	}
	return strings.Join(parts, ", ")
}

// HasSliceParam checks if any parameter is a slice.
func HasSliceParam(params []Param) bool {
	for _, p := range params {
		if p.IsSlice {
			return true
		}
	}
	return false
}

// ReturnCountExpr generates the expression for counting return slice elements.
// For slice returns, it looks for a slice input param (uses len()) or falls back to a
// _count parameter that the caller must provide.
func ReturnCountExpr(params []Param, ret Return) string {
	if !ret.IsSlice {
		return "0"
	}
	for _, p := range params {
		if p.IsSlice {
			return "len(" + p.Name + ")"
		}
	}
	return "_count"
}
